'use-strict'

export const SET_LOGGED_USER_DATA='SET_LOGGED_USER_DATA';
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_TOAST_MESSAGE = "SET_TOAST_MESSAGE"

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const READ_TODO_SUCCESS = "READ_TODO_SUCCESS"
export const SET_LOADER = "SET_LOADER"
export const CHECK_INTERNET_CONNECTION='CHECK_INTERNET_CONNECTION';


export const ADD_REMOVE_CART_SUCCESS = "ADD_REMOVE_CART_SUCCESS"
export const ADD_REMOVE_WISHLIST_SUCCESS  = "ADD_REMOVE_WISHLIST_SUCCESS"
export const REMOVE_CART_SUCCESS  = "REMOVE_CART_SUCCESS"
export const ADD_CART_API_SUCCESS = "ADD_CART_API_SUCCESS"